/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vgc.zuoyunjin16825;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @ZuoyunJin16825
 */
public class ManageStudentAssignmentsResults extends javax.swing.JFrame implements ProgramInterface{

    /**
     * Creates new form AddAndEditExamsResults
     */
    public ManageStudentAssignmentsResults() {
        initComponents();
         showExamData();
    }

    public Connection getConnection() {
        try {
            String dbUrl = "jdbc:mysql://localhost:3306/vgc?useSSL=false";
            String userid = "root";
            String userps = "P6agztsg";
            Connection myConn = DriverManager.getConnection(dbUrl, userid, userps);
            return myConn;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    String UserID;
    public void getUserID(){
     try{
          
          FileReader file2= new FileReader("UserID.txt");
          BufferedReader buffer=new BufferedReader(file2);
          String line;
          while((line = buffer.readLine()) != null){
             UserID=line;
          }
        buffer.close();    
      }
      catch(IOException e){
          System.out.println("A write error has occured");
      }
    }
    public ArrayList<AssignmentsData> AssignmentsList() {
        getUserID();
        ArrayList<AssignmentsData> AssignmentsList = new ArrayList();
        Connection myConn = getConnection();
        String sql = "Select AssignmentsGradeBook.* from ((Timetable INNER JOIN Courses ON Timetable.CoursesID = Courses.CoursesID) inner join AssignmentsGradeBook on AssignmentsGradeBook.CoursesID = Courses.CoursesID)where FacultyID="+UserID;
        try {
            Statement myStmt = myConn.createStatement();
            ResultSet myRs = myStmt.executeQuery(sql);
            AssignmentsData AssignmentsDataTable;
            while (myRs.next()) {

                AssignmentsDataTable = new AssignmentsData(myRs.getInt("StudentID"), myRs.getInt("CoursesID"), myRs.getString("AssignmentsDate"), myRs.getInt("AssignmentsResults"));
                AssignmentsList.add(AssignmentsDataTable);
            }
        } catch (Exception exc) {
            exc.printStackTrace();
        }
        return AssignmentsList;
    }
    
    
    public void refreshTableData(String message)
   {    
               // refresh jtable data
               DefaultTableModel model = (DefaultTableModel)AssignmentTable.getModel();
               model.setRowCount(0);
               showExamData();
               
               JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");  
   }
    
    
    public void showExamData() {
        ArrayList<AssignmentsData> list = AssignmentsList();
        DefaultTableModel model = (DefaultTableModel) AssignmentTable.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getSID();
            row[1] = list.get(i).getCID();
            row[2] = list.get(i).getAMD();
            row[3] = list.get(i).getAMR();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CID = new javax.swing.JTextField();
        SID = new javax.swing.JTextField();
        AMD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AssignmentTable = new javax.swing.JTable();
        Update = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        AMR = new javax.swing.JTextField();
        AMRC = new javax.swing.JLabel();

        SID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIDActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Student Assignment Result");

        AssignmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StudentID", "CoursesID", " AssignmentDate", " AssignmentResults"
            }
        ));
        AssignmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssignmentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AssignmentTable);

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        AMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AMR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AMRC))
                                .addGap(82, 82, 82)
                                .addComponent(Update)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AMR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(3, 3, 3)
                .addComponent(AMRC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(Back)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SIDActionPerformed

    private void AMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AMRActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new MenuT().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void AssignmentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignmentTableMouseClicked
        // Get The Index Of The Slected Row 
        int i = AssignmentTable.getSelectedRow();

        TableModel model = AssignmentTable.getModel();

        // Display Slected Row In JTexteFields
        SID.setText(model.getValueAt(i, 0).toString());

        CID.setText(model.getValueAt(i, 1).toString());

        AMD.setText(model.getValueAt(i, 2).toString());

        AMR.setText(model.getValueAt(i, 3).toString());

    }//GEN-LAST:event_AssignmentTableMouseClicked

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
    if (AMD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Assignment date CAN NOT BE NULL!!!");
        } else {
            Connection myConn = getConnection();
            String sql = "update AssignmentsGradeBook set AssignmentsResults = ? where StudentID = ? and AssignmentsDate = ? and CoursesID = ?";
            
            
            
            Pattern pAMR = Pattern.compile("\\d{1,3}");
            Matcher mAMR = pAMR.matcher(AMR.getText());
            boolean isAMRValid = mAMR.matches();
            
            if (isAMRValid) {
                AMRC.setText("Valid");
                AMRC.setForeground(Color.BLUE);    
                 try {
                PreparedStatement pst = myConn.prepareStatement(sql);
                pst.setString(1, AMR.getText().trim());
                pst.setString(2, SID.getText().trim());
                pst.setString(3, AMD.getText().trim());
                pst.setString(4, CID.getText().trim());
                pst.executeUpdate();
                 refreshTableData("Updated");
            } catch (Exception exc) {
                exc.printStackTrace();
            }
            } else {
                AMRC.setText("Enter number from 0 to 100");
                AMRC.setForeground(Color.red);
            }
            
           
    }                   
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudentAssignmentsResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudentAssignmentsResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudentAssignmentsResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudentAssignmentsResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudentAssignmentsResults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AMD;
    private javax.swing.JTextField AMR;
    private javax.swing.JLabel AMRC;
    private javax.swing.JTable AssignmentTable;
    private javax.swing.JButton Back;
    private javax.swing.JTextField CID;
    private javax.swing.JTextField SID;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
